# Generated by Django 4.2.7 on 2025-10-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_document_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_document_url',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_verified_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=20),
        ),
    ]
