# Generated by Django 4.2.7 on 2025-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_id_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='admin_notes',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, help_text="Customer's chosen username", max_length=150),
        ),
    ]
