# Generated by Django 4.2.7 on 2025-10-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_admin_notes_customer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
