# Generated by Django 4.2.7 on 2025-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_full_name_customer_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPaymentMethod',
        ),
    ]
