# Generated by Django 4.2.7 on 2025-10-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_delete_customerpaymentmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerActivityLog',
        ),
    ]
