# Generated by Django 4.2.7 on 2025-10-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_delete_customeractivitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRideHistory',
        ),
    ]
