# Generated by Django 4.2.7 on 2025-10-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='account_balance',
        ),
    ]
