# Generated by Django 4.2.7 on 2025-10-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_sessiontracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_mfa_enabled',
            field=models.BooleanField(default=False, help_text='Designates whether the user has MFA enabled.'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='mfa_code_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiry time for the MFA code.', null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='mfa_email_code',
            field=models.CharField(blank=True, help_text='Temporary code sent via email.', max_length=6, null=True),
        ),
    ]
