# Generated by Django 4.2.7 on 2025-10-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminuser_is_mfa_enabled_adminuser_mfa_code_expiry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
