# Generated by Django 4.2.7 on 2025-10-05 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geofencing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='color_code',
            field=models.CharField(default='#3388ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zone',
            name='polygon_points',
            field=models.JSONField(default=list, help_text='List of lat/lng points defining the polygon'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='performance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='total_rentals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='total_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='unique_bikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='unique_customers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneperformance',
            name='zone',
            field=models.ForeignKey(db_column='zone_firebase_id', on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='geofencing.zone', to_field='firebase_id'),
        ),
        migrations.AlterField(
            model_name='zoneviolation',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zoneviolation',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='zoneviolation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zoneviolation',
            name='rental_id',
            field=models.CharField(blank=True, help_text='Firebase rental document ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zoneviolation',
            name='violation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zoneviolation',
            name='zone',
            field=models.ForeignKey(db_column='zone_firebase_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='geofencing.zone', to_field='firebase_id'),
        ),
    ]
