# Generated by Django 4.2.7 on 2025-10-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geofencing', '0002_alter_zone_center_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZonePerformance',
        ),
    ]
