# Generated by Django 4.2.7 on 2025-10-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='current_zone_id',
            field=models.CharField(blank=True, help_text='Firebase zone document ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('OFFLINE', 'Offline'), ('ARCHIVED', 'Archived')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bike',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bikelocationhistory',
            name='bike',
            field=models.ForeignKey(db_column='bike_firebase_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='bikes.bike', to_field='firebase_id'),
        ),
        migrations.AlterField(
            model_name='bikelocationhistory',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bikelocationhistory',
            name='synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bikeperformance',
            name='performance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bikeperformance',
            name='revenue_generated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikeperformance',
            name='ride_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bikeperformance',
            name='total_distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bikeperformance',
            name='total_duration',
            field=models.IntegerField(default=0, help_text='Total minutes'),
        ),
        migrations.AlterField(
            model_name='bikeperformance',
            name='utilization_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of day bike was in use', max_digits=5),
        ),
    ]
