# Generated by Django 4.2.7 on 2025-10-28 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_current_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikePerformance',
        ),
    ]
