# Generated by Django 4.2.7 on 2025-10-26 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_rename_full_name_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_id', models.CharField(db_index=True, help_text='Document ID from Firebase payments collection', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Payment amount', max_digits=10)),
                ('payment_type', models.CharField(choices=[('GCASH', 'GCash'), ('PAYMAYA', 'PayMaya'), ('CARD', 'Credit/Debit Card'), ('BANK', 'Bank Transfer'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Method used for payment (e.g., GCash, PayMaya)', max_length=20)),
                ('payment_status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Status of the payment transaction', max_length=20)),
                ('payment_account_info', models.CharField(blank=True, help_text='Reference info like transaction ID or masked account (Firebase: paymentAccount)', max_length=255)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Timestamp when the payment was made', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_firebase_id', help_text='Customer who made the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='customers.customer', to_field='firebase_id')),
                ('ride', models.OneToOneField(blank=True, db_column='ride_firebase_id', help_text='The ride associated with this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='customers.customerridehistory', to_field='firebase_id')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['firebase_id'], name='payments_firebas_766240_idx'), models.Index(fields=['customer'], name='payments_custome_e2a41e_idx'), models.Index(fields=['ride'], name='payments_ride_fi_96c4a4_idx'), models.Index(fields=['payment_date'], name='payments_payment_aebcb7_idx'), models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'), models.Index(fields=['payment_type'], name='payments_payment_ba7b87_idx')],
            },
        ),
    ]
