# Generated by Django 4.2.7 on 2025-10-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_payment_status'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ride',
            field=models.OneToOneField(blank=True, db_column='ride_firebase_id', help_text='The ride associated with this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='rides.ride', to_field='firebase_id'),
        ),
    ]
