# Generated by Django 4.2.7 on 2025-10-27 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_delete_customerridehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_id', models.CharField(db_index=True, help_text='Document ID from Firebase support_requests collection', max_length=255, unique=True)),
                ('issue', models.TextField(help_text='Description of the issue')),
                ('response', models.TextField(blank=True, help_text='Admin response to the issue')),
                ('app_version', models.CharField(blank=True, help_text='App version when the issue was reported', max_length=50)),
                ('test_id', models.CharField(blank=True, db_index=True, help_text='Test identifier from Firebase', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='pending', help_text='Current status of the support request', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Priority level of the support request', max_length=20)),
                ('assigned_to', models.CharField(blank=True, help_text='Admin user assigned to this request', max_length=255)),
                ('submission_time', models.CharField(blank=True, help_text='Formatted submission time from Firebase', max_length=255)),
                ('timestamp', models.BigIntegerField(blank=True, db_index=True, help_text='Unix timestamp in milliseconds from Firebase', null=True)),
                ('submission_datetime', models.DateTimeField(blank=True, db_index=True, help_text='Converted datetime from timestamp', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_firebase_id', help_text='Customer who submitted the support request (Firebase: userId)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='customers.customer', to_field='firebase_id')),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'db_table': 'support_requests',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['firebase_id'], name='support_req_firebas_285dd9_idx'), models.Index(fields=['customer'], name='support_req_custome_4c08fc_idx'), models.Index(fields=['status'], name='support_req_status_ba7e97_idx'), models.Index(fields=['priority'], name='support_req_priorit_33fc04_idx'), models.Index(fields=['timestamp'], name='support_req_timesta_d74b43_idx'), models.Index(fields=['submission_datetime'], name='support_req_submiss_0c11d1_idx')],
            },
        ),
    ]
