# Generated by Django 4.2.7 on 2025-10-26 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0002_alter_bike_current_latitude_and_more'),
        ('customers', '0006_delete_customeractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_id', models.CharField(db_index=True, help_text='Document ID from Firebase ride_logs collection', max_length=255, unique=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Timestamp when the ride started', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Timestamp when the ride ended', null=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Calculated duration of the ride in minutes')),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ride_path_points', models.JSONField(default=list, help_text='List of coordinate points recorded during the ride')),
                ('start_zone_id', models.CharField(blank=True, help_text='Firebase zone ID where ride started', max_length=255)),
                ('end_zone_id', models.CharField(blank=True, help_text='Firebase zone ID where ride ended', max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Calculated distance of the ride in kilometers', max_digits=10)),
                ('amount_charged', models.DecimalField(decimal_places=2, default=0, help_text='Amount charged for the ride', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('UNKNOWN', 'Unknown')], default='PENDING', help_text='Status of the payment associated with this ride', max_length=20)),
                ('rental_status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='ACTIVE', help_text='Current status of the ride/rental', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(blank=True, db_column='bike_firebase_id', help_text='Bike used for the ride (Firebase: bikeId)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='bikes.bike', to_field='firebase_id')),
                ('customer', models.ForeignKey(blank=True, db_column='customer_firebase_id', help_text='Customer who took the ride (Firebase: userId)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='customers.customer', to_field='firebase_id')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'db_table': 'rides',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['firebase_id'], name='rides_firebas_d86df6_idx'), models.Index(fields=['customer'], name='rides_custome_96fe77_idx'), models.Index(fields=['bike'], name='rides_bike_fi_da7981_idx'), models.Index(fields=['start_time'], name='rides_start_t_8aebc5_idx'), models.Index(fields=['rental_status'], name='rides_rental__c43ff3_idx'), models.Index(fields=['payment_status'], name='rides_payment_290b1d_idx')],
            },
        ),
    ]
