# Generated by Django 4.2.7 on 2025-10-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('UNKNOWN', 'Unknown')], default='PENDING', help_text='Status of the payment associated with this ride', max_length=20),
        ),
    ]
