"""
Bike Models - PostgreSQL Analytics Models
Primary data stored in Firebase, synced to PostgreSQL for analytics

This file contains 3 models:
1. Bike - Main bike model
2. BikeLocationHistory - Historical location tracking
3. BikePerformance - Daily performance metrics
"""

from django.db import models
import uuid


class Bike(models.Model):
    """
    Bike analytics model synced from Firebase
    
    Firebase Structure:
    bikes/{bike_id}/
        - bike_model: string
        - status: string
        - current_location: GeoPoint
        - current_zone_id: string
        - bike_type: string
        - created_at: timestamp
    """
    
    BIKE_TYPE_CHOICES = [
        ('REGULAR', 'Regular'),
        ('ELECTRIC', 'Electric'),
        ('MOUNTAIN', 'Mountain'),
    ]
    
    STATUS_CHOICES = [
        ('AVAILABLE', 'Available'),
        ('IN_USE', 'In Use'),
        ('MAINTENANCE', 'Under Maintenance'),
        ('OFFLINE', 'Offline'),
    ]
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    firebase_id = models.CharField(
        max_length=255, 
        unique=True, 
        db_index=True,
        help_text="Document ID from Firebase"
    )
    bike_model = models.CharField(max_length=100)
    bike_type = models.CharField(max_length=20, choices=BIKE_TYPE_CHOICES, default='REGULAR')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='AVAILABLE')
    
    # Current location (synced from Firebase GeoPoint)
    current_latitude = models.DecimalField(
        max_digits=10, 
        decimal_places=7, 
        null=True, 
        blank=True,
        help_text="Current latitude coordinate"
    )
    current_longitude = models.DecimalField(
        max_digits=10, 
        decimal_places=7, 
        null=True, 
        blank=True,
        help_text="Current longitude coordinate"
    )
    
    # Zone assignment
    current_zone_id = models.CharField(
        max_length=255, 
        null=True, 
        blank=True,
        help_text="Firebase zone document ID where bike is currently located"
    )
    
    # Sync metadata
    synced_at = models.DateTimeField(auto_now=True, help_text="Last sync from Firebase")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'bikes'
        verbose_name = 'Bike'
        verbose_name_plural = 'Bikes'
        indexes = [
            models.Index(fields=['firebase_id']),
            models.Index(fields=['status']),
            models.Index(fields=['bike_type']),
            models.Index(fields=['current_zone_id']),
        ]
        ordering = ['-created_at']
    
    def __str__(self):
        return f"{self.firebase_id} - {self.bike_model} ({self.get_status_display()})"
    
    @property
    def has_location(self):
        """Check if bike has current location data"""
        return self.current_latitude is not None and self.current_longitude is not None


class BikeLocationHistory(models.Model):
    """
    Historical bike locations synced from Firebase subcollection
    
    Firebase Structure:
    bikes/{bike_id}/location_history/{timestamp}/
        - location: GeoPoint
        - speed: number
        - recorded_at: timestamp
    """
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    bike = models.ForeignKey(
        Bike, 
        on_delete=models.CASCADE, 
        related_name='location_history',
        to_field='firebase_id',
        db_column='bike_firebase_id',
        help_text="Reference to bike by Firebase ID"
    )
    latitude = models.DecimalField(max_digits=10, decimal_places=7)
    longitude = models.DecimalField(max_digits=10, decimal_places=7)
    speed = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        null=True, 
        blank=True,
        help_text="Speed in km/h"
    )
    recorded_at = models.DateTimeField(help_text="When this location was recorded")
    synced_at = models.DateTimeField(auto_now=True, help_text="When synced to PostgreSQL")
    
    class Meta:
        db_table = 'bike_location_history'
        verbose_name = 'Bike Location History'
        verbose_name_plural = 'Bike Location History'
        indexes = [
            models.Index(fields=['bike', 'recorded_at']),
            models.Index(fields=['recorded_at']),
        ]
        ordering = ['-recorded_at']
    
    def __str__(self):
        return f"{self.bike.firebase_id} at {self.recorded_at}"


class BikePerformance(models.Model):
    """
    Daily bike performance metrics (aggregated from rental data)
    Generated by Celery tasks for analytics dashboard
    """
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    bike = models.ForeignKey(
        Bike,
        on_delete=models.CASCADE,
        related_name='performance_records',
        to_field='firebase_id',
        db_column='bike_firebase_id'
    )
    performance_date = models.DateField(help_text="Date for this performance record")
    ride_count = models.IntegerField(default=0, help_text="Number of rides completed")
    total_distance = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        default=0,
        help_text="Total distance traveled in km"
    )
    total_duration = models.IntegerField(default=0, help_text="Total ride duration in minutes")
    revenue_generated = models.DecimalField(
        max_digits=10, 
        decimal_places=2, 
        default=0,
        help_text="Total revenue generated"
    )
    utilization_rate = models.DecimalField(
        max_digits=5, 
        decimal_places=2, 
        default=0,
        help_text="Percentage of day bike was in use (0-100)"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'bike_performance'
        verbose_name = 'Bike Performance'
        verbose_name_plural = 'Bike Performance'
        unique_together = ['bike', 'performance_date']
        indexes = [
            models.Index(fields=['bike', 'performance_date']),
            models.Index(fields=['performance_date']),
        ]
        ordering = ['-performance_date']
    
    def __str__(self):
        return f"{self.bike.firebase_id} - {self.performance_date} ({self.ride_count} rides)"